### ISSUE TITLE
Running ESNUEL on Google Colab

### ISSUE THREAD

**Issue by NicolaiRee** [jensengroup/ESNUEL#2]
@NicolaiRee I'm not sure if I'm running the same problem, but I got the same output. 

I was trying to run the code in Jupyter notebook on google Colab with following code:
(I tried original and esnuel-xtb branch and it gave the same output)
calc_MAA_and_MCA('O=C1CCCC1', 'test')

Output:
Electrophilic sites: 
Electrophilic sites: 
 ['Ketone', 'double_bond'] 
 [1, 0] 
 [-inf, -inf]
Nucleophilic sites: 
 ['Ketone'] 
 [0] 
 [-inf]
([[1, 0]],
 [['Ketone', 'double_bond']],
 [['CC1([O-])CCCC1', 'CO[C-]1CCCC1']],
 [[-inf, -inf]],
 [[[[None, 'test/reac01/conf01/gfn1/test_reac01_conf01_gfn1_opt.sdf'],
    [None,
     'test/reac01prodE01/conf02/gfn1/test_reac01prodE01_conf02_gfn1_opt.sdf']],
   [[None, 'test/reac01/conf01/gfn1/test_reac01_conf01_gfn1_opt.sdf'],
    [None,
     'test/reac01prodE02/conf04/gfn1/test_reac01prodE02_conf04_gfn1_opt.sdf']]]],
 [[0]],
 [['Ketone']],
 [['CO[C+]1CCCC1']],
 [[-inf]],
 [[[[None, 'test/reac01/conf01/gfn1/test_reac01_conf01_gfn1_opt.sdf'],
    [None,
     'test/reac01prodN01/conf05/gfn1/test_reac01prodN01_conf05_gfn1_opt.sdf']]]])
 
 I tried this molecule on the website esnuel.org and it gave MAA value =  287.90 kJ/mol when only using xTB
Was I doing something wrong in my code? Please let me know if you need more information.

 Thank you!

_Originally posted by @tranJen in https://github.com/jensengroup/ESNUEL/issues/1#issuecomment-2248698617_

**Comment by NicolaiRee** [comment]
Hi @tranJen, 
First of all, thanks for your interest in ESNUEL.

Your question is related to using ESNUEL on Google Colab, which is kind of a separate topic so I created a new issue.

I have not tested this, but I have some suggestions to resolve this issue.
1) You can only use the esnuel-xtb branch on Google Colab, which means omitting the ORCA calculations.
2) Update all the paths in accordance with the Google Colab directory.
3) Make sure the conda environment is correctly installed.
4) Make sure that you are indeed using the correct conda environment and Python (this is probably the main problem with Google Colab).
5) Check whether the xTB calculations are running. Are you getting any output?

Let me know, if it works out :)

**Comment by suongbatran** [comment]
@NicolaiRee 
Thanks for your quick response! It works fine now!

The reason I switched to run on Google Colab is that I got this error while running the same code in Python

OSError: [Errno 8] Exec format error: '/Users/suongsuong/ESNUEL/dep/xtb-6.5.1/bin/xtb'

Do you have any suggestion for this error so I could run it? Thank you!

**Comment by suongbatran** [comment]
Additionally, I was also trying to run the molecule below and it took too long to execute (56 minute) and having some warning lines printed out.
calc_MAA_and_MCA ('COC(OC)C1=CC=CC=C1C(CC#N)C(=O)C1=CC=CC=C1','38244374')


WARNING! Input/output mismatch for 38244374_reac01prodN07_conf19_gfn1.xyz
WARNING! Input/output mismatch for 38244374_reac01prodN07_conf09_gfn1.xyz
WARNING! Input/output mismatch for 38244374_reac01prodN08_conf13_gfn1.xyz
WARNING! Input/output mismatch for 38244374_reac01prodN07_conf15_gfn1.xyz
WARNING! Input/output mismatch for 38244374_reac01prodN10_conf17_gfn1.xyz
WARNING! Input/output mismatch for 38244374_reac01prodN10_conf14_gfn1.xyz
Reactant - #1
Electrophilic sites: 
 ['Ketone', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'triple_bond', 'triple_bond'] 
 [15, 5, 6, 7, 8, 9, 10, 16, 17, 18, 19, 20, 13, 14] 
 [324.8950227628229, 228.2765343763167, 222.53779225540347, 238.88027248633443, 237.06264945978182, 230.14678748860024, 298.5039798943035, 217.48509174614446, 242.76429967433796, 310.2610479714058, 213.09299454517895, 312.8631951928837, 377.03852872003336, 353.5916262109531]
Nucleophilic sites: 
 ['Ketone', 'Nitrile', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'double_bond', 'atom_with_lone_pair'] 
 [16, 14, 5, 6, 7, 8, 9, 10, 17, 18, 19, 20, 1] 
 [416.06729245500173, 515.1353170002985, 430.9410862882214, 344.3497142268752, 351.24113765356014, 338.31198240994127, 465.08301971742185, 403.5411494105647, 324.0677282414981, 410.5000837482221, 320.6025730636611, 314.17111899208976, 387.19546268318663]

What does the warning mean? Is there anyway to run it faster?

I also tried this molecule on esnuel.org and it said
"The number of heavy atoms (23) exceeds the limit of 20" I don't know if that is something set for the website, or does it have something to do with the code. 

Thank you so much for your help!

**Comment by NicolaiRee** [comment]
> OSError: [Errno 8] Exec format error: '/Users/suongsuong/ESNUEL/dep/xtb-6.5.1/bin/xtb'

This error message shows that you have a problem of running xTB on your device. Please have a look at "https://github.com/grimme-lab/xtb" and install xTB on your device in accordance with their documentation. 
This should resolve the problem.

**Comment by NicolaiRee** [comment]
The error message "WARNING! Input/output mismatch" notifies you that the QM geometry optimizations for the specified calculations have resulted in connectivity changes (atoms are bonded differently in the input and output). It will be highlighted in the visual output (see "Error Log (Reactant, Product)"), if the lowest energy conformer has connectivity issues.

Due to the limited size of our webserver (2 CPU cores), we have limited the allowed submissions to molecules with a maximum of 20 heavy atoms.

It seems strange that your molecule: "COC(OC)C1=CC=CC=C1C(CC#N)C(=O)C1=CC=CC=C1" takes 56 minutes. However, you can speed up the calculations by allowing the calculations to use more than 2 CPU cores.
